# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"

  # Network Configuration
  config.vm.network "private_network", ip: "192.168.56.30"
  config.vm.network "public_network"

  # Provider Configuration
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1600"
  end

  # Provisioning with Shell Script
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt update
    sudo apt install -y apache2 ghostscript libapache2-mod-php mysql-server php php-bcmath php-curl php-imagick php-intl php-json php-mbstring php-mysql php-xml php-zip

    sudo mkdir -p /srv/www
    # Before creating the directories, ensure they have the correct ownership
    sudo chown -R www-data:www-data /srv/www

    # Download and extract WordPress
    curl -O https://wordpress.org/latest.tar.gz
    tar -zxvf latest.tar.gz -C /srv/www
    rm latest.tar.gz
	
	# Set ownership for WordPress directory
    sudo chown -R www-data:www-data /srv/www/wordpress

    # Configure Apache
    cat > /etc/apache2/sites-available/wordpress.conf <<EOF
<VirtualHost *:80>
    DocumentRoot /srv/www/wordpress
    <Directory /srv/www/wordpress>
        Options FollowSymLinks
        AllowOverride Limit Options FileInfo
        DirectoryIndex index.php
        Require all granted
    </Directory>
    <Directory /srv/www/wordpress/wp-content>
        Options FollowSymLinks
        Require all granted
    </Directory>
</VirtualHost>
EOF

    sudo a2ensite wordpress
    sudo a2enmod rewrite
    sudo a2dissite 000-default

    # MySQL Setup
    mysql -u root -e 'CREATE DATABASE wordpress;'
    mysql -u root -e 'CREATE USER wordpress@localhost IDENTIFIED BY "admin123";'
    mysql -u root -e 'GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON wordpress.* TO wordpress@localhost;'
    mysql -u root -e 'FLUSH PRIVILEGES;'

    # Configure WordPress
    sudo -u www-data cp /srv/www/wordpress/wp-config-sample.php /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/database_name_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/username_here/wordpress/' /srv/www/wordpress/wp-config.php
    sudo -u www-data sed -i 's/password_here/admin123/' /srv/www/wordpress/wp-config.php
	
	# Ensure correct ownership for wp-config.php
    sudo chown www-data:www-data /srv/www/wordpress/wp-config.php

    systemctl restart mysql
    systemctl restart apache2
  SHELL
end
