# Vagrantfile for VMware ESXi

Vagrant.configure('2') do |config|
  config.vm.provision :reload
  # Use the VMware ESXi provider
  config.vm.provider :vmware_esxi do |esxi|
    esxi.esxi_hostname = '192.168.1.35'
    esxi.esxi_username = 'root'
    esxi.esxi_password = '***************'
 #  esxi.vmx_template_path = "path/to/your/template.vmx" # Update to the path of your VM template
  end

  # Define web01, web02, and db01 virtual machines
  config.vm.define 'web01' do |web01|
 #  web01.vm.guest = :linux
    web01.vm.box = 'generic/ubuntu1710'
    web01.vm.hostname = 'web01'
    web01.vm.network 'private_network', ip: '192.168.11.172'
 #  esxi.guest_username = 'vagrant'
 #  esxi.guest_memsize = '2048'
 #  esxi.guest_numvcpus = '2'
  end

  config.vm.define 'web02' do |web02|
 #  web02.vm.guest = :linux
    web02.vm.box = 'generic/ubuntu1710'
    web02.vm.hostname = 'web02'
    web02.vm.network 'private_network', ip: '192.168.11.173'
 #  esxi.guest_username = 'vagrant'
 #  esxi.guest_memsize = '2048'
 #  esxi.guest_numvcpus = '2'
  end

  config.vm.define 'db01' do |db01|
 #  db01.vm.guest = :linux
    db01.vm.box = 'generic/centos7'
    db01.vm.hostname = 'db01'
    db01.vm.network 'private_network', ip: '192.168.11.174'
 #  esxi.guest_username = 'vagrant'
 #  esxi.guest_memsize = '2048'
 #  esxi.guest_numvcpus = '2'
    # Provisioning for db01 (You can add your provisioning scripts here)
   db01.vm.provision 'shell', inline: <<-SHELL
      # Add your provisioning commands here
      yum install -y wget unzip mariadb-server -y
      systemctl start mariadb
      systemctl enable mariadb
    SHELL
  end

  # Additional configuration if needed
end

